import type { Metadata } from 'next';
import { notoSansKr } from 'styles';
import { StyledComponentsRegistry, RecoilRootWrapper, ReactQueryProvider } from '@/lib';
import './styles/globals.css';
import { BaseHeader } from 'components';

export const metadata: Metadata = {
  title: '손만두',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={notoSansKr.regular.className} suppressHydrationWarning={true}>
        <ReactQueryProvider>
          <RecoilRootWrapper>
            <StyledComponentsRegistry>
              <BaseHeader></BaseHeader>
              {children}
            </StyledComponentsRegistry>
          </RecoilRootWrapper>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
