import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import {
  StyledComponentsRegistry,
  RecoilRootWrapper,
  ReactQueryProvider,
} from '@/lib'
import './styles/globals.css'

export const metadata: Metadata = {
  title: '손만두',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      {/* <body suppressHydrationWarning={true}> */}
      <body suppressHydrationWarning={true}>
        <ReactQueryProvider>
          <RecoilRootWrapper>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </RecoilRootWrapper>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
