h2:
  username: "H2_USERNAME"
  password: "H2_PASSWORD"

mysql:
  username: "MYSQL_USERNAME"
  password: "MYSQL_PASSWORD"

s3:
  access-key: "S3_ACCESS_KEY"
  secret-key: "S3_SECRET_KEY"

jwt:
  secret: "JWT_SECRET_KEY"

sonmandu:
  email: "EMAIL"